name: ExploitsX
main: me.bait.exploitsx.ExploitsX
version: 1.7.3.auto
author: io.github.izdabait
description: Top of the line exploit fixer for large servers impacted by lag / crash exploits.
api-version: 1.16
depend: [ PlaceholderAPI ]
commands:
  e:
    description: Basic ExploitsX command.
  exploits:
    description: Basic ExploitsX command.
  pl:
    description: ExploitsX pluginlist override.
  xitem:
    description: spawn a shulker of items (for opped players only)
  uitem:
    description: spawn an unlimited item (for opped players only)
permissions:
  exploitsx.*:
    description: Admin ExploitsX permission
    default: op
  exploitsx.snick:
    description: ExploitsX Nick