name: ExploitsX
main: me.bait.exploitfixer.exploitfixer
version: 1.6.12.turret
author: io.github.izdabait
description: Top of the line exploit fixer for large servers impacted by lag / crash exploits.
api-version: 1.16
commands:
  e:
    description: Basic ExploitsX command.
  exploits:
    description: Basic ExploitsX command.
  pl:
    description: ExploitsX pluginlist override.
  stats:
    description: ExploitsX stats command.
    usage: /stats <playername>.
  stat:
    description: ExploitsX stats command.
    usage: /stat <playername>.
  statistics:
    description: ExploitsX stats command.
    usage: /statistics <playername>.    
  xitem:
    description: spawn a shulker of items (for opped players only)
  uitem:
    description: spawn an unlimited item (for opped players only)
permissions:
  exploitsx.*:
    description: Admin ExploitsX permission
  exploitsx.snick:
    description: ExploitsX Nick
depend: [PlaceholderAPI]